name: Build Image

on:
  # push:
  #   branches: [ "main" ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ayaka-notes/overleaf
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
    - name: Build Overleaf image
      run: |
        cd server-ce/
        make build-base
        make build-community
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./.github/workflows
        file: ./.github/workflows/Dockerfile
        push: true
        tags: ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}





    
