name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      unconditional-invoking:
        description: 'Deploy Manually'
        type: boolean
        required: true
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd server-ce/
        make build-base
        make build-community
